### ISSUE TITLE
ella-server will not build on Windows

### ISSUE THREAD

**Issue by sydduckworth** [BlackrockNeurotech/ella#13]
`ella-server` won't build on Windows because it requires `protobuf-src`, which does not support Windows (see MaterializeInc/rust-protobuf-native#4).

The best solution for now is probably to change `protobuf-src` to only be a dependency on Unix, add instructions for installing `protoc` on Windows, and update the CI to install `protoc`.

**Comment by benesch** [comment]
FYI, the latest version of protobuf-src now builds with CMake rather than autotools. I've not yet tested this, but it may "just work" with Windows now.
